FORMAT: 1A
HOST: http://lifeplans-api.herokuapp.com

# lifeplans-api

Lifeplans-api is a an API for developers to build bucketlist applications

## Bucketlists Collection [/bucketlists]

### List All Bucketlist [GET]

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
                "id": 3,
                "title": "Weeding",
                "created_at": "2016-02-08T14:14:09.610Z",
                "updated_at": "2016-02-08T14:14:09.610Z",
                "user_id": 3
            },
            {
                "id": 4,
                "title": "Seeding",
                "created_at": "2016-02-08T14:14:13.349Z",
                "updated_at": "2016-02-08T14:14:13.349Z",
                "user_id": 3
            }
        ]

### Successful bucketlist creation [POST]

+ Request (application/json)
        
        {
            "title": "Weeding"
        }

+ Response 200 (application/json) 
    
        {
            "id": 4,
            "title": "Weeding",
            "created_at": "2016-02-08T14:14:13.349Z",
            "updated_at": "2016-02-08T14:14:13.349Z",
            "user_id": 3
        }

## User Creation [/users/register]

### successful user creation [POST]


+ Request (application/json)
        
        {
            "username": "Daniju",
            "password": "password",
            "password_confirmation": "password"
        }


+ Response 200 (application/json)

        {
            "feedback": "You are welcome to Lifeplans"
        }

## User Login [/auth/login]

### Successful user login [POST]

+ Request (application/json)

        {
            "username": "Daniju",
            "password": "password"
        }

+ Response 200 (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE0NTUxMTMwMjd9.zT61jaREEOy0TW2nvHGSBXLzcPAXdvBw4wWRVWyNfOU"
        }